[package]
name = "winteros-detect-hardware"
version = "0.1.0"
edition = "2021"

[dependencies]
serde_json = "1.0.140"
regex = "1.11.1"
reqwest = { version = "0.12.15", features = ["blocking"] }
futures-util = "0.3.31"
