[package]
name = "winteros-detect-hardware"
version = "1.0.0"
edition = "2021"

[dependencies]
serde_json = "1.0.140"
reqwest = { version = "0.12.15", features = ["blocking"] }
nix = { version = "0.29.0", features = ["user"] }
system_info = { git = "https://github.com/Winter-OS/system_info.git" }
